constants:
  api:
    prefix: /api/auth
  enum:
    scan-package: com.green.common

server:
  port: ${AUTH_PORT}

spring:
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-jpa.yaml
      - optional:classpath:application-auth.yaml
      - optional:file:.env[.properties]
  application:
    name: auth-service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_HOST}:${DB_PORT}/my_gu_auth?createDatabaseIfNotExist=true&characterEncoding=UTF-8
    #jdbc: — JAVA-DB 연결
    #log4jdbc: — log4jdbc 라이브러리. DB에 날아가는 SQL 쿼리문을 로그로 보기 좋게 출력
    #mysql: — MySQL DB를 쓴다는 선언입니다.
    #?createDatabaseIfNotExist=true — DB가 없으면 자동으로 만들어줍니다. 팀원이 처음 실행할 때 DB가 없어도 오류 없이 자동 생성됩니다.
    #&characterEncoding=UTF-8 — 한글이 깨지지 않도록 인코딩(문자 저장 방식)을 UTF-8로 지정합니다.
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    # [수신] Member 캐시 정보를 받기 위한 설정
    consumer:
      group-id: auth-service-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.green.common.model,com.green.common.kafka"
  mail:
    host: smtp.gmail.com        # Gmail SMTP 서버 주소
    port: 587                   # STARTTLS 방식의 표준 포트
    username: ${MAIL_USERNAME}  # 발송에 사용할 Gmail 주소
    password: ${MAIL_PASSWORD}  # Gmail 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true            # SMTP 인증 사용 (필수)
          starttls:
            enable: true        # 보안 연결(TLS) 사용 (필수)
