constants:
  api:
    prefix: /api/academic

server:
  port: 8080

spring:
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-jpa.yaml
      - optional:classpath:application-auth.yaml
      - optional:file:.env[.properties]
  application:
    name: academic-service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_ACADEMIC}?createDatabaseIfNotExist=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 하이버네이트 7의 메타데이터 조회 버그 방지
        temp:
          use_jdbc_metadata_defaults: false
  kafka:
    bootstrap-servers: kafka.infra.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
outbox:
  enabled: true