constants:
  api:
      prefix: /api/member
  file:
    directory: ${FILE_DIRECTORY}
    max-size: 5242880  # 5MB

server:
  port: ${MEMBER_PORT}

spring:
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-jpa.yaml
      - optional:classpath:application-auth.yaml
      - optional:file:.env[.properties]
  application:
    name: member-service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_HOST}:${DB_PORT}/my_gu_member?createDatabaseIfNotExist=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  kafka:
    bootstrap-servers: localhost:9092
    # [발행] student, professor 이벤트를 Outbox에 담아 보냄
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # [수신] Major 캐시 정보를 받기 위한 설정
    consumer:
      group-id: member-service-group
      auto-offset-reset: earliest          # 추가: 놓친 메시지 처음부터 재수신
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # 추가
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.green.common.model,com.green.common.kafka"

outbox:
  enabled: true

core-service:
  url: http://${SERVICE_HOST}:${CORE_PORT}
logging:
  level:
    org.springframework.web: DEBUG