management:
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: gateway
  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-auth.yaml
      - optional:file:.env[.properties]
  cloud:
    gateway:
      # 4.0.x 버전 Servlet Gateway의 핵심 설정 프리픽스
      server:
        webmvc:
          actuator:
            enabled: true
          cors: # cors 허용
            configurations:
              '[/**]':
                allowed-origins: [ "http://localhost:5173", "http://localhost:5174" ]
                allowed-methods: [ "*" ]
                allowed-headers: [ "*" ]
                allow-credentials: true
                max-age: 3600

          # 라우팅 설정
          routes:
            - id: auth-service
              uri: http://${SERVICE_HOST}:${AUTH_PORT}
              predicates:
                - Path=/api/auth/**, /api/code

            - id: member-service
              uri: http://${SERVICE_HOST}:${MEMBER_PORT}
              predicates:
                - Path=/api/member/**, /api/member/**

            - id: core-service
              uri: http://${SERVICE_HOST}:${CORE_PORT}
              predicates:
                - Path=/api/core/**

            - id: academic-service
              uri: http://${SERVICE_HOST}:${ACADEMIC_PORT}
              predicates:
                - Path=/api/academic/**

server:
  port: ${GATEWAY_PORT}