constants:
  exception:
    common-handler:
      enabled: true

spring:
  datasource:
    hikari:
      maximum-pool-size: 5 # 기본값 10에서 줄임 (서비스 규모에 따라 조절)
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 50 # 배치작업 크기 설정
        format_sql: true # 쿼리문 보기편하게 포맷팅
        order_updates: true # JPA Batch 작업 활성화
    show-sql: true # JPA가 쿼리문 로그에 출력